require: rubocop-rspec
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'script/**/*'
    - 'Vagrantfile'
    - 'Guardfile'
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
  Exclude:
    - 'db/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'app/services/expa_sign_up.rb'
    - 'app/services/send_to_podio.rb'
    - 'app/controllers/gv_participants_controller.rb'
    - 'app/controllers/ge_participants_controller.rb'
    - 'app/controllers/gt_participants_controller.rb'
    - 'app/controllers/concerns/gv_participant_fields.rb'
    - 'app/controllers/concerns/ge_participant_fields.rb'
    - 'app/controllers/concerns/gt_participant_fields.rb'
Metrics/LineLength:
  Exclude:
    - 'db/seeds/**'
    - 'db/schema.rb'
    - 'app/services/send_to_podio.rb'
    - 'app/controllers/gv_participants_controller.rb'
    - 'app/controllers/ge_participants_controller.rb'
    - 'app/controllers/gt_participants_controller.rb'
    - 'app/controllers/concerns/gv_participant_fields.rb'
    - 'app/controllers/concerns/ge_participant_fields.rb'
    - 'app/controllers/concerns/gt_participant_fields.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/services/expa_sign_up.rb'
    - 'app/services/send_to_podio.rb'
    - 'app/controllers/gv_participants_controller.rb'
    - 'app/controllers/ge_participants_controller.rb'
    - 'app/controllers/gt_participants_controller.rb'
    - 'app/controllers/concerns/gv_participant_fields.rb'
    - 'app/controllers/concerns/ge_participant_fields.rb'
    - 'app/controllers/concerns/gt_participant_fields.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/send_to_podio.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/send_to_podio.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/gt_participants_controller.rb'
Style/ClassVars:
  Exclude:
    - 'app/services/send_to_podio.rb'
Style/NumericPredicate:
  Exclude:
    - 'app/services/send_to_podio.rb'
RSpec/NestedGroups:
  Max: 4
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - 'db/seeds/**'
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/SymbolArray:
  Exclude:
    - 'db/migrate/**'
Style/SymbolProc:
  Exclude:
    - 'db/migrate/**'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'
