require: rubocop-rspec
AllCops:
  Exclude:
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Vagrantfile'
    - 'Guardfile'
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
  Exclude:
    - 'db/schema.rb'
Metrics/LineLength:
  Exclude:
    - 'db/seeds/**'
    - 'db/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'app/services/expa_sign_up.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/services/expa_sign_up.rb'
RSpec/NestedGroups:
  Max: 4
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - 'db/seeds/**'
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/SymbolArray:
  Exclude:
    - 'db/migrate/**'
Style/SymbolProc:
  Exclude:
    - 'db/migrate/**'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'
