# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
SALT: "\xCE%\x94\x89\x7FC\xF8\xA8\x14\x9A\n\xA2\xBCaK\xDB\xCD\x86\x1F\xC7\x9F\xE7\xE8l\xC4\xFA\xAF\xB9\xABQ\xE32"
KEY: "\xA4\xF1$\x16\x81\xFE\xDA\x0E\xADv\xA8\xE2\xBD\x94\x95\xC8\xBC~-\xA0VP\x13\xCB\x9C\x98\xBB/ 0uY"
