COUNTRY: 'bra'
ENV: 'staging'
SLACK_WEBHOOK_URL: ''
SALT:
AWS_REGION: 'sa-east-1'
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
PODIO_API_KEY: ''
PODIO_API_SECRET: ''
PODIO_USERNAME: ''
PODIO_PASSWORD: ''
PODIO_APP_GV: '15290822'
PODIO_APP_GE: '17057629'
PODIO_APP_GT: '17057001'
PODIO_APP_ICX_APPLICATIONS_GV: '22140491'
PODIO_APP_ICX_APPLICATIONS_GE: '22140751'
PODIO_APP_ICX_APPLICATIONS_GT: '22140766'
SENTRY_DSN: 'sentry dsn'