concurrency: 1
delay: 30
queues:
  - [databazi_sign_up_queue, 1]
  - [databazi_podio_queue_new, 1]
  - [survey_processor, 1]
  - [impact_brazil_referral, 1]
  - [update_podio_id, 1]
  - [exchange_student_host, 1]
  - [membership_queue, 1]
  - [expa_to_podio, 1]
