# Universities

INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9227', 'Amazonas', 'Amazonas - Otras universidades e institutos', 'Amazonas', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('10613', 'Ancash', 'Ancash - Otras universidades e institutos', 'Ancash', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8820', 'Ancash', 'Huaraz - Universidad Católica Los Ángeles de Chimbote', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8824', 'Ancash', 'Huaraz - Universidad Cesar Vallejo', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8822', 'Ancash', 'Huaraz - Universidad Nacional del Santa', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8823', 'Ancash', 'Huaraz - Universidad Nacional San Pedro', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8821', 'Ancash', 'Huaraz - Universidad Nacional Santiago Antúnez de Mayolo', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8825', 'Ancash', 'Huaraz - Universidad Peruana de Ciencias e Informátic', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8819', 'Ancash', 'Huaraz - Universidad San Pedro', 'Huaraz', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9228', 'Apurimac', 'Apurimac - Otras universidades e institutos', 'Apurimac', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5765', 'Arequipa', 'Arequipa - ISUR', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5768', 'Arequipa', 'Arequipa - Otras universidades e institutos', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5766', 'Arequipa', 'Arequipa - SENATI', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5767', 'Arequipa', 'Arequipa - TECSUP', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5759', 'Arequipa', 'Arequipa - Universidad Alas Peruanas', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5764', 'Arequipa', 'Arequipa - Universidad Andina Néstor Cáceres Velásquez', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5755', 'Arequipa', 'Arequipa - Universidad Católica de Santa María', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5754', 'Arequipa', 'Arequipa - Universidad Católica San Pablo', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5763', 'Arequipa', 'Arequipa - Universidad La Salle', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5762', 'Arequipa', 'Arequipa - Universidad Nacional de San Agustín de Arequipa', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5761', 'Arequipa', 'Arequipa - Universidad San Martin de Porres', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5760', 'Arequipa', 'Arequipa - Universidad Tecnológica del Perú', 'Arequipa', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5769', 'Ayacucho', 'Ayacucho - Otras universidades e institutos', 'Ayacucho', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5773', 'Cajamarca', 'Cajamarca - Otras universidades e institutos', 'Cajamarca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5772', 'Cajamarca', 'Cajamarca - Universidad Nacional de Cajamarca', 'Cajamarca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5771', 'Cajamarca', 'Cajamarca - Universidad Privada Antonio Guillermo Urrelo', 'Cajamarca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5770', 'Cajamarca', 'Cajamarca - Universidad Privada del Norte', 'Cajamarca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5889', 'Cusco', 'Cusco - Otras universidades e institutos', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5888', 'Cusco', 'Cusco - Universidad Alas Peruanas', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5856', 'Cusco', 'Cusco - Universidad Andina del Cusco', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5874', 'Cusco', 'Cusco - Universidad Global del Cusco', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5847', 'Cusco', 'Cusco - Universidad Nacional de San Antonio Abad del Cusco', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5863', 'Cusco', 'Cusco - Universidad Peruana Austral del Cusco', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5881', 'Cusco', 'Cusco - Universidad Tecnológica de los Andes', 'Cusco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9232', 'Huancavelica', 'Huancavelica - Otras universidades e institutos', 'Huancavelica', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('7656', 'Huánuco', 'Huánuco - Otras universidades e institutos', 'Huánuco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8862', 'Huánuco', 'Huánuco - Universidad Alas Peruanas', 'Huánuco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8863', 'Huánuco', 'Huánuco - Universidad Católica los Angeles de Chimbote', 'Huánuco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8816', 'Huánuco', 'Huánuco - Universidad de Huánuco', 'Huánuco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8818', 'Huánuco', 'Huánuco - Universidad Nacional Agraria de la Selva', 'Huánuco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8817', 'Huánuco', 'Huánuco - Universidad Nacional Hermilio Valdizán', 'Huánuco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5906', 'Ica', 'Ica - Otras universidades e institutos', 'Ica', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5904', 'Ica', 'Ica - Universidad Alas Peruanas', 'Ica', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5903', 'Ica', 'Ica - Universidad Nacional San Luis Gonzaga', 'Ica', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5902', 'Ica', 'Ica - Universidad Privada de Ica S.A.', 'Ica', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5905', 'Ica', 'Ica - Universidad Privada San Juan Bautista SAC', 'Ica', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5897', 'Junin', 'Junin - Otras universidades e institutos', 'Junin', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5894', 'Junin', 'Huancayo - Universidad Alas Peruanas', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5890', 'Junin', 'Huancayo - Universidad Continental', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5891', 'Junin', 'Huancayo - Universidad Nacional del Centro del Perú', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5892', 'Junin', 'Huancayo - Universidad Peruana Los Andes', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5895', 'Junin', 'Huancayo - Universidad Privada del Centro', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5893', 'Junin', 'Huancayo - Universidad Roosevelt', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5896', 'Junin', 'Huancayo - Universidad Santo Tomas', 'Huancayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5779', 'La Libertad', 'La Libertad - Otras universidades e institutos', 'La Libertad', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5793', 'La Libertad', 'Trujillo - Universidad Alas Peruanas', 'Trujillo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5789', 'La Libertad', 'Trujillo - Universidad Católica de Trujillo', 'Trujillo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5780', 'La Libertad', 'Trujillo - Universidad Nacional de Trujillo', 'Trujillo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5797', 'La Libertad', 'Trujillo - Universidad Privada Antenor Orrego', 'Trujillo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5795', 'La Libertad', 'Trujillo - Universidad Privada del Norte', 'Trujillo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5791', 'La Libertad', 'Trujillo - Universidad Privada Leonardo Da Vinci', 'Trujillo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5787', 'Lambayeque', 'Lambayeque - Otras universidades e institutos', 'Lambayeque', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5782', 'Lambayeque', 'Chiclayo - Universidad Alas Peruanas', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5774', 'Lambayeque', 'Chiclayo - Universidad Católica Santo Toribio de Mogrovejo', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5785', 'Lambayeque', 'Chiclayo - Universidad de Chiclayo', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5786', 'Lambayeque', 'Chiclayo - Universidad de Lambayeque', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5777', 'Lambayeque', 'Chiclayo - Universidad Nacional Pedro Ruiz Gallo', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8815', 'Lambayeque', 'Chiclayo - Universidad Particular de Chiclayo', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5775', 'Lambayeque', 'Chiclayo - Universidad San Martin de Porres', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5781', 'Lambayeque', 'Chiclayo - Universidad Señor de Sipán', 'Chiclayo', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5878', 'Lima', 'Lima - ADEX', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5753', 'Lima', 'Lima - CIBERTEC', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5859', 'Lima', 'Lima - Escuela de Empresarios IPAE', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8844', 'Lima', 'Lima - Fala Bem', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5857', 'Lima', 'Lima - IDAT', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5875', 'Lima', 'Lima - Instituto Leo Design', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5911', 'Lima', 'Lima - Instituto Peruano de Arte y Diseño', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5756', 'Lima', 'Lima - Instituto Toulouse Lautrec', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5915', 'Lima', 'Lima - ISIL', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5913', 'Lima', 'Lima - Otras universidades e institutos', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5907', 'Lima', 'Lima - Pontificia Universidad Católica del Perú', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5917', 'Lima', 'Lima - SENATI', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8960', 'Lima', 'Lima - TECSUP', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5908', 'Lima', 'Lima - Universidad Alas Peruanas', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8831', 'Lima', 'Lima - Universidad Andina Néstor Cáceres Velásquez', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8829', 'Lima', 'Lima - Universidad Antonio Ruiz de Montoya', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5920', 'Lima', 'Lima - Universidad Científica del Sur', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8832', 'Lima', 'Lima - Universidad de Ciencias y Artes de América Latina', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5758', 'Lima', 'Lima - Universidad de Ingeniería y Tecnología', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5918', 'Lima', 'Lima - Universidad de Lima', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5850', 'Lima', 'Lima - Universidad de Piura', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5887', 'Lima', 'Lima - Universidad del Pacífico', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5914', 'Lima', 'Lima - Universidad ESAN', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5884', 'Lima', 'Lima - Universidad Femenina del Sagrado Corazón', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5909', 'Lima', 'Lima - Universidad Inca Garcilaso de la Vega', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5910', 'Lima', 'Lima - Universidad Jaime Bausate y Meza', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5919', 'Lima', 'Lima - Universidad Nacional Agraria La Molina', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5871', 'Lima', 'Lima - Universidad Nacional de Ingeniería', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5873', 'Lima', 'Lima - Universidad Nacional del Callao', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5868', 'Lima', 'Lima - Universidad Nacional Federico Villarreal', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5866', 'Lima', 'Lima - Universidad Nacional Mayor de San Marcos', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('10614', 'Lima', 'Lima - Universidad SISE', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5849', 'Lima', 'Lima - Universidad Nacional Tecnológica de Lima Sur', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5883', 'Lima', 'Lima - Universidad Peruana Cayetano Heredia', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5880', 'Lima', 'Lima - Universidad Peruana de Ciencias Aplicadas S.A.C.', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5757', 'Lima', 'Lima - Universidad Privada César Vallejo', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5912', 'Lima', 'Lima - Universidad Privada del Norte', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5852', 'Lima', 'Lima - Universidad Ricardo Palma', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5916', 'Lima', 'Lima - Universidad San Ignacio de Loyola', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5862', 'Lima', 'Lima - Universidad San Martín de Porres', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5865', 'Lima', 'Lima - Universidad Tecnológica del Perú', 'Lima', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('10124', 'Loreto', 'Loreto - Otras universidades e institutos', 'Loreto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8827', 'Loreto', 'Iquitos - Universidad Científica del Perú', 'Iquitos', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8826', 'Loreto', 'Iquitos - Universidad Nacional de la Amazonía Peruana', 'Iquitos', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8828', 'Loreto', 'Iquitos - Universidad Privada de la Selva Peruana', 'Iquitos', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9229', 'Madre de Dios', 'Madre de Dios - Otras universidades e institutos', 'Madre de Dios', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('10615', 'Moquegua', 'Moquegua - Otras Universidades e Institutos', 'Moquegua', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8834', 'Moquegua', 'Moquegua - Universidad Jose Carlos Mariategui', 'Moquegua', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8833', 'Moquegua', 'Moquegua - Universidad Naconal de Moquegua UNAM', 'Moquegua', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9230', 'Pasco', 'Pasco - Otras universidades e institutos', 'Pasco', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5831', 'Piura', 'Piura - Otras universidades e institutos', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5838', 'Piura', 'Piura - Universidad Alas Peruanas', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5842', 'Piura', 'Piura - Universidad César Vallejo', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5845', 'Piura', 'Piura - Universidad de Piura', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5843', 'Piura', 'Piura - Universidad Nacional de Piura', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5840', 'Piura', 'Piura - Universidad Privada Antenor Orrego', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5833', 'Piura', 'Piura - Universidad Privada del Norte', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5835', 'Piura', 'Piura - Universidad San Pedro ', 'Piura', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8857', 'Puno', 'Juliaca - Otras universidades e institutos', 'Juliaca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8855', 'Puno', 'Juliaca - Universidad Andina Néstor Cáceres Velásquez', 'Juliaca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8856', 'Puno', 'Juliaca - Universidad Peruana Unión', 'Juliaca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8554', 'Puno', 'Puno - Otras universidades e institutos', 'Puno', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8836', 'Puno', 'Puno - Universidad Andina Néstor Cáceres Velasquez', 'Puno', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8835', 'Puno', 'Puno - Universidad Nacional del Altiplano', 'Puno', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8854', 'Puno', 'Puno - Universidad Privada San Carlos de Puno', 'Puno', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8861', 'San Martin', 'Nueva Cajamarca - Universidad Católica Sedes Sapientiae', 'Nueva Cajamarca', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8845', 'San Martin', 'San Martin - Otras universidades e institutos', 'San Martin', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8837', 'San Martin', 'Tarapoto - Universidad Alas Peruanas', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8860', 'San Martin', 'Tarapoto - Universidad Catolica los Angeles de Chimbote', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8838', 'San Martin', 'Tarapoto - Universidad Cientfica del Perú', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8859', 'San Martin', 'Tarapoto - Universidad de la Amazonia Mario Pelaez Bazan S.A.C.', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8839', 'San Martin', 'Tarapoto - Universidad Nacional de San Martín', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8840', 'San Martin', 'Tarapoto - Universidad Peruana Unión', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('8841', 'San Martin', 'Tarapoto - Universidad Privada César Vallejo', 'Tarapoto', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5816', 'Tacna', 'Tacna - Instituto Neuman', 'Tacna', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5811', 'Tacna', 'Tacna - Otras universidades e institutos', 'Tacna', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5822', 'Tacna', 'Tacna - Universidad Alas Peruanas', 'Tacna', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5820', 'Tacna', 'Tacna - Universidad Nacional Jorge Basadre Grohmann', 'Tacna', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('5823', 'Tacna', 'Tacna - Universidad Privada de Tacna', 'Tacna', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9233', 'Tumbes', 'Tumbes - Otras universidades e institutos', 'Tumbes', now(), now());
INSERT INTO universities (expa_id, department, name, city, created_at, updated_at) VALUES('9231', 'Ucayali', 'Ucayali - Otras universidades e institutos', 'Ucayali', now(), now());

# Local Committees

INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Arequipa', 613, 1, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Cajamarca', 1922, 2, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Católica', 669, 16, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Chiclayo', 1665, 3, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Cusco', 1890, 4, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Huancayo', 1718, 5, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Huánuco', 2363, 6, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Ica', 1720, 7, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Lima', 589, 8, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Pacífico', 1432, 9, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('MC Peru', 1768, 10, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Piura', 160, 11, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Puno', 2364, 12, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('San Marcos', 269, 17, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Tacna', 1717, 13, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Tarapoto', 2365, 14, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('Trujillo', 1716, 15, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('URP', 116, 19, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('USMP', 1732, 18, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('EduardoLandia', 2382, -1, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('EduardoLandia', 2383, -1, now(), now(), true);
INSERT INTO local_committees (name, expa_id, podio_id, created_at, updated_at, active) VALUES('EduardoLandia', 2384, -1, now(), now(), true);
